### ISSUE TITLE
Best way to redeploy/refresh pso-dbs?

### ISSUE THREAD

**Issue by StuartWhelan** [purestorage/pso-csi#108]
I have updated my values.yaml to include resource requests for my pso-db's (which are currently using 70% of the clusters memory), and then ran a helm upgrade.

What is the safest way to trigger the pso-db redeployment with new resource request suggestions?

**Comment by haibinxie** [comment]
the helm upgrade with db pod resource limit is not implemented yet, the best way is to start with a fresh installation. If there is no content (volumes/snapshots) in db right now, it can be uninstalled and reinstalled. if there is already content in db, it is not well supported right now, we are working on a tool to reconstruct the content of DB and also a upgrade path to set the memory limit, for this PI.

**Comment by haibinxie** [comment]
here is how to make it work for now, before we implement a complete upgrade path:
1. config correct resource limits in values.yaml, use helm upgrade to upgrade it. I think for your case, you want resource limits in below. (note it is limits not requests)
resources:
 limits:
   cpu: "1"
   memory: "1Gi"
2. delete cockroach operator pod via kubectl delete pod , find the pod name via:
root@docker-desktop:/go/src/pso.purestorage.com/k8s# kubectl get pod -n default | grep operator
pso-db-cockroach-operator-fd98886f-l6nmb  1/1    Running  0     7m25s
3. patch all db statefulsets with the resource limits one by one. via kubectl set resources statefulset pso-db-1 --limits cpu=1,memory=512Mi
for example in the setup below, there are 5 statefulsets named pso-db-*-0, all of them should be patched
root@docker-desktop:/go/src/pso.purestorage.com/k8s# kubectl get statefulset -n default  | grep pso-db
pso-db-1             1/1       38m
pso-db-2             1/1       38m
pso-db-3             1/1       38m
pso-db-4             1/1       23m
pso-db-5             1/1       11m

**Comment by StuartWhelan** [comment]
Thank you for the instructions.

I have successfully done this on our test cluster, and a few days later our prod cluster. A few notes for anyone who follows..

- Of course use the namespace you installed your pure csi into, which is probably not default.
- It is probably a good idea to check your pso-db cluster is healthy before you start. Use `kubectl --namespace pure-csi get intrusion` and check the status is Live, you have 5/5 in a ready state, that there is 0 Under-Replicated and 0 Unavailable. You can ignore the Ranges value.
- After patching the resources on each pso-db pod it is probably a good idea to wait for the pso-db cluster to recover before moving onto the next one. You can do this via get intrusion. This is what it looked like when I patched the resources on a pod:

```
$ kubectl --namespace pure-csi get intrusion --watch
NAME     STATUS   READY   RANGES   UNDER-REPLICATED   UNAVAILABLE   AS-OF
pso-db   Live     5/5     128      0                  0             2020-11-08T20:14:18Z
pso-db   Live     5/5     128      0                  0             2020-11-08T20:14:20Z
pso-db   Live     4/5     128      0                  0             2020-11-08T20:14:31Z
pso-db   Live     4/5     167      83                 0             2020-11-08T20:14:31Z
pso-db   Live     4/5     167      83                 0             2020-11-08T20:14:32Z
pso-db   Live     4/5     128      83                 0             2020-11-08T20:14:37Z
pso-db   Live     4/5     89       0                  0             2020-11-08T20:14:42Z
pso-db   Live     5/5     128      0                  0             2020-11-08T20:14:44Z
pso-db   Live     5/5     128      0                  0             2020-11-08T20:14:47Z
```

You can see it is healthy (5/5, 128, 0, 0) before I start, then a pso-db drops, the under-replicated increases, then the pso-db comes back online the the cluster healths. I waited for the cluster to return to 5/5, 128, 0, 0 before I moved on to the next pso-db. 

- The number of ranges will almost certainly be different on your cluster, and the number may change during operations. This is benign and can safely be ignored.

**Comment by sdodsley** [comment]
@StuartWhelan this is great information.
Thank you for validating our process in a real-world environment.
We will take your comments and ensure they are reflected in our process description.
