### ISSUE TITLE
Readiness probe failed with connection refused

### ISSUE THREAD

**Issue by nitroman02** [purestorage/pso-csi#130]
Hi, I've tried deploying PSO to verify function with our //FA M20, but faced "Readiness probe failed" and some PSO pods doesn't boot well.
May I have any advice?

Out environment
- PSO 6.0.5
- CentOS Linux release 7.9.2009 (Core)
-3master, 3worker of 6 nodes, and 1 HAproxy node for control plain
-Kubernetes Ver.
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", 
  GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", 
  GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", 
  GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", 
  GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- pod network: Calico with default values
 https://docs.projectcalico.org/manifests/calico.yaml

I got several output of kubectl command.
[kubectl.log](https://github.com/purestorage/pso-csi/files/5929661/kubectl.log)

Issued "helm install" with following values.yaml.
[values.yaml.log](https://github.com/purestorage/pso-csi/files/5929671/values.yaml.log)

**Comment by sdodsley** [comment]
@nitroman02 can you confirm that all the PSO pre-requisites have been met for the worker nodes? 

That includes IPv4 forwarding being enabled, a time sync service (such as ntpd or chronyd) is correctly installed and configured, multipathing software is installed and running (with the Pure stanza in the config file) and iSCSI software is installed and running.

It is also worth confirming your iSCSI dataplane communication is correct and you can ping the FlashArray iSCSI target IP addresses from all worker nodes.

After confirming these details, can you do the following:
- Check if any volumes were created on your FlashArray. The volume names would be similar to `<clusterID>-pso-db_<digits>`
- Provide the output of the following commands:

`kubectl get all -n <spo-namespace>`

`kubectl describe` for all pods in the PSO namespace

`kubectl logs -n <pso-namespace> pso-csi-controller-0 pure-csi-container`

From these we will better be able to help diagnose the issue.

**Comment by nitroman02** [comment]
@sdodsley  Hi, Thank you for replying.
(I rebuild the cluster with K8s ver. 1.20.2, but the situation have not changed yet.)
I think the environment have met the requisites.
As a screenshot I attached, on M20, "HOSTs" have been configured with the name of worker nodes & its IQNs, and some "-pso-db_" volume have been created and connected. (These mean all requisites have been met correctly?)
I also attached logs you told.
Thank you.
 
![host_view](https://user-images.githubusercontent.com/68048464/107123796-0f63dd80-68e3-11eb-9e50-d6930b701211.png)
[20210207_010432_10.10.132.211.log](https://github.com/purestorage/pso-csi/files/5937186/20210207_010432_10.10.132.211.log)

**Comment by sdodsley** [comment]
@nitroman02 I suspect this is your error, as seen in the describes.
`Failed to pull image "purestorage/k8s:v6.0.5": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`
Due to the popularity of PSO we are starting to see this issue more frequently. 
Whilst we work out how we can resolve this issue, I suggest you keep trying to install until the downloads are successful.

**Comment by dsupure** [comment]
Thanks @sdodsley.
Yes, this is due to docker hub limit issue: https://www.docker.com/increase-rate-limits

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and 
Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

We are working on buying an unlimited license. Thanks for your patient.

**Comment by nitroman02** [comment]
Thank you, @sdodsley , @dsupure.
As you said, the cause was the limitation of docker hub.
My colleague could get some images from purestorage repo., and build local repository.
I could get all PSO pods running successfully with that repo. 
Thanks!
