### ISSUE TITLE
HashiCorp Nomad Support

### ISSUE THREAD

**Issue by jjthiessen** [purestorage/pso-csi#132]
This is less of an issue, and more of a series of questions (with implicit improvement suggestions).

CSI support has been available in HashiCorp Nomad (as a beta feature) for almost a year.
My understanding is that it is also available in at least a couple other orchestrators (Mesos, Cloud Foundry).

I haven't tried setting up pso-csi in our Nomad environment, but presumably 5.x _should_ just work (after reading through all the YAML and translating things into job specs for the controller and node services).

With the advent of pso-csi 6.x, Pure's CSI plugin is no longer stateless.
Is it possible to leverage a manually deployed/managed cockroach DB cluster, or does the architecture of pso-csi 6.x require that the plugin be able to directly manage the cockroach cluster via K8S.
That is, is pso-csi a CSI plugin with an external metadata storage requirement; or is pso-csi actually dependent on Kubernetes APIs?

Is there any hope for running pso-csi 6.x+ in a non-Kubernetes environment with CSI plugin support available?
If so, is there any intent on making this an officially supported deployment option?

Does anybody reading this have examples of pso-csi 5.x or 6.x working with Nomad in the wild?
If so, are you willing to contribute examples to the documentation?

**Comment by sdodsley** [comment]
PSO 6 does require our internal CockroachDB with its own FlashAraays/FlashBlade backed storage and cannot leverage an external DB. It is also dependent on Kubernetes APIs.
We have no support for Nomad for a lot of the reasons you have listed.
For PSO 5 it might be possible, but that version is now deprecated.

For the future, we are planning to merge PSO into Portworx (following our acquisition) and therefore there are no plans for making PSO in its current incarnation support anything other than k8s.

**Comment by jjthiessen** [comment]
That both makes sense, and gives me several more follow-up questions (licensing implications, timing, etc); however, those conversations are probably more appropriate to have directly with our contacts at Pure (vs hijacking the issue tracker for PSO).

Thanks for your help.
