### ISSUE TITLE
FC connectivity requirement

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#135]
Can you clarify the requirement: "FC Supported on Bare-metal K8s installations only"? If we intend to run multiple KVMs for k8s compute on top of our physical nodes, would that impact FC connectivity for those virtual machines?

**Comment by sdodsley** [comment]
Please clarify how the KVM VMs will be presented with FC vWWNs and how these can be guaranteed to be persistent over reboots of the VM. 
We have seen issues with the vWWN changing on reboot which causes the persistent volumes to loose connection to the VMs.

**Comment by dsupure** [comment]
@aboje : Any update from your side? We have not verified PSO in KVM environment. But we guess PSO should running fine as long as @sdodsley 's concern is addressed. Let me know if you have more questions.

**Comment by aboje** [comment]
We are going through testing and checking with our HW vendor now. I will report our findings when this is complete.

**Comment by aboje** [comment]
We verified with our HW vendor that this will not be possible. Closing issue.
