### ISSUE TITLE
[Question] CockroachDB version

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#141]
This chart is using cockroach 19.2.3 which is a year old.

During testing of a supposed memory-leak in a previous issue https://github.com/purestorage/pso-csi/issues/91 (which was not, `limits` had to be set), we tried more recent image of the DB.

It was not part of the resolution but  I cannot downgrade to default version of this chart since I migrated to 20.x. 

Forcing this image is still OK with current version of the chart.

I wonder if you plan to update the version used ?

**Comment by dingyin** [comment]
Yes, we have a plan to update the version in the next release soon.

**Comment by mscbpi** [comment]
Closed with 6.1.1
