### ISSUE TITLE
ImagePullSecrets in Helm charts for Docker Registry

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#142]
I recently encounter a situation where pods -not only PSO's- were evicted due to some pressure on nodes. 

Then it went into a kind of scheduling loop:
- PSO operator was down
- Apps' Pods were not able to dettach/attach volume, no CSI available
- PSO Pods/DB could not terminate because of the `finalizer` not being available
- Apps and PSO Pods were getting into a crashloop and imagepull
- Rate limiting on dockerhub was reached for image pulling
- PSO could never start even after forcing finalizing the pods, **because of docker hub blocking the image pull**.

I sorted it out by creating a secret with my dockerhub credentials -we have a paid account- and setting the `imagePullSecrets` on PSO's Deployments&StatefulSets. It appears I could not do that through the helm charts and it will be replaced in next update.

Once nodes health OK, PSO was back again thanks to the `secret`, the cluster recovered. 

It is the first time I am getting blocked in the middle of a troubleshooting because of docker's limits. 

Is there a way to specify the secret in the `helm` `values.yaml` ?

**Comment by dingyin** [comment]
We are updating the DockerHub account and will fix the rate limiting issue for image pulling.

**Comment by mscbpi** [comment]
Isn't it also the limit the client has ? Docker hub added quota on unauthenticated pull recently, and I am sure I reached this one,  not yours. Problem was solved by adding my credentials (paid account without limits) in ImagePullSecrets that I set on PSO's StatefulSets and Deployments.

**Comment by sdodsley** [comment]
@mscbpi The issue was with the Pure Storage docker account in that it had not been upgraded after Docker changed the pull limits for free accounts.
This has been rectified and the Pure Storage Docker account has unlimited pull with zero throttling now.

**Comment by mscbpi** [comment]
I reread the [documentation about docker hub rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) and as far as I understand the quota is applied to the puller not the publisher, thus it is important that we can set our credentials in imagePullSecret as documented in the link above (see Kubernetes). From a practical point of view, referencing the secret from the helm chart's values.yaml. Don't you think? @sdodsley

**Comment by sdodsley** [comment]
Whilst I agree that there are pull limits for individual users, the issue we were seeing was that the Pure docker account hosting the images was a free account and therefore had limits placed on the number of image requests from it. These limits no longer exist as we have upgraded to a  Team account. 
Should we see an uptick in issues with individual user accounts experiencing pull issues, we can certainly look into your suggestion as a possible solution.

**Comment by mscbpi** [comment]
@sdodsley  thank you for your message, I cannot find this information anywhere. As we are also docker hub users may you be kind enough to highlight where requests limits applied to image publisher is documented and how you may know when quota is reached ? I can only see pull limits. btw when we were facing the issue with your image it was just with any image trying to be pulled unauthenticated from docker hub so that was obviously our limit applied. thanks

**Comment by mscbpi** [comment]
@sdodsley actually I confirmed the opposite so you may review it:

https://www.docker.com/pricing/resource-consumption-updates

"Rate limits for Docker image pulls are based on the account type of the user requesting the image - not the account type of the image’s owner. These are defined on the pricing page."

**Comment by sdodsley** [comment]
@mscbpi Yes - I agree with you after reading the blog post. Docker do not make it obvious and there is an implication in their pricing guidelines that the pull limits are based on the hosting account as well.
I will raise this issue with our Product Management team as it could impact not just PSO and its ultimate merging with Portworx, but also Portworx's as well.

**Comment by mscbpi** [comment]
So PSO will merge with portworx ? 😀

**Comment by sdodsley** [comment]
Yes - we have a roadmap for the complete integration by the end of this calendar year.
if you would like us to give you a presentation on the PSO -> PX roadmap please let me know by emailing me at simon@purestorage.com
