### ISSUE TITLE
[Question] Deploy PSO on control plane / master nodes ?

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#143]
Some examples of pod scheduling mentions the master nodes as appropriate nodes to run PSO. 
https://github.com/purestorage/pso-csi/blob/master/docs/csi-controller-attach-detach.md

Being a component of the control-plane, this makes sense.  Is this considered as a best practice, assuming the nodes are capable of hosting them ? 

- I tend not to mix K8s components with other's on master nodes, and PSO is quite a heavy workload with its cockroachDB. 
- My clusters are too small (8 nodes) to imagine a (worker) node pool designated to host just that
- My worker nodes would be glad to save some memory for user workloads rather than a CSI driver.

Any insights on what's the best practice ?

**Comment by dingyin** [comment]
@mscbpi Could you let me know what version of PSO you are using?

**Comment by mscbpi** [comment]
Version 6.0.5

Concerning resources Limits are used and were used before you set them up in helm charts by default, so to avoid cockroach using all the system memory. Cockroach aligns its system memory with limit sets so no OOM kill either. Still all considered PSO is resource-consuming
