### ISSUE TITLE
failed to create snapshot in k8s 1.20

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#158]
We recently upgraded to k8s 1.20.  I am having troubles creating volumesnapshots. Here is the error:

spec:
    snapshotClassName: pure-snapshotclass
    snapshotContentName: ""
    source:
      apiGroup: null
      kind: PersistentVolumeClaim
      name: pvc-nginx
  status:
    creationTime: "2021-04-05T13:22:48Z"
    error:
      message: 'Failed to create snapshot: selfLink was empty, can''t make reference'
      time: "2021-04-05T13:23:11Z"
    readyToUse: false
    restoreSize: null

I am using snapshot.storage.k8s.io/v1alpha1, which is still included in k8s 1.20. 

$ kubectl api-versions | grep snap
snapshot.storage.k8s.io/v1alpha1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-31T15:33:39Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-31T16:42:32Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

We are using: image: purestorage/k8s:5.2.0

It looks like this issue is referenced here, but I'm not sure how that helps us. Is an upgrade to PSO 6.x required? 
https://github.com/kubernetes/kubernetes/issues/94660

**Comment by Pure-AdamuKaapan** [comment]
@aboje are you currently using PSO 5.x (looks like 5.2.0)? If so, can you please go ahead and open this on github.com/purestorage/helm-charts instead? Thanks!

**Comment by Pure-AdamuKaapan** [comment]
That being said, it looks like that issue is resolved in csi-snapshotter v2+, which we use in PSO 6, so an upgrade would fix that and is probably recommended for k8s 1.20 anyways.

**Comment by aboje** [comment]
Created https://github.com/purestorage/helm-charts/issues/256
