### ISSUE TITLE
pso 5 to 6 upgrade. namespace concern

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#159]
I am planning an upgrade from PSO 5 to 6. I have read the warnings regarding the requirement to keep PSO in the same namespace when upgrading to PSO 6.1. Our challenge is that we specified 'pure-csi' as the namespace in the PSO 5 helm installation, but it installed in the default namespace. 

[(default)]$ helm get values pure-storage-driver
USER-SUPPLIED VALUES:
arrays:
  FlashArrays:
    { REDACTED }
namespace:
  pure: pure-csi

[(default)]$ helm ls -n default
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
pure-storage-driver     default         1               2020-08-17 21:26:44.021943316 +0000 UTC deployed        pure-csi-1.2.0  1.2.0

[(default)]$ helm ls -n pure-csi
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
[(default)]$

Will this be a problem when we run the PSO 6 upgrade steps?

**Comment by sdodsley** [comment]
You have misunderstood the reference to `namespace`.

In the `values.yaml` file for PSO 5 the value for `namespace: pure:` is nothing to do with the k8s namespace, hence why we changed this field to be `clusterID` in PSO 6. There was a lot of confusion around this.

You have installed PSO 5 in the `default` k8s namespace and so you MUST install PSO 6 in the same k8s namespace, however using the `default` k8s namespace is never a good idea.

The `namespace: pure:` value you have currently, ie `pure-csi` is used as a prefix for PSO volumes/shares created on backend arrays. **This value MUST be the same value as you assign to `clusterID` for PSO 6 or the upgrade will fail.**

**Comment by aboje** [comment]
Understood, thank you for the clarification.
