### ISSUE TITLE
Process to enable snapshots on PSO6

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#165]
We had the ability to run snapshots under PSO5 and kubernetes 1.18/1.19. 
When we upgraded to 1.20 we could no longer create snapshots. Details: https://github.com/purestorage/pso-csi/issues/158
We were not able to run the helm upgrade due to this: https://github.com/purestorage/pso-csi/issues/164 
We ran the helm installation with upgrade=false and a new clusterID. 
PSO6 looks like it installed correctly. I can create PVCs, but I cannot create snapshots. 

I still see the old pure-snapshotclass:
$ k get volumesnapshotclass pure-snapshotclass
NAME                 AGE
pure-snapshotclass   240d

When I try to apply the new definition (https://raw.githubusercontent.com/purestorage/pso-csi/master/pure-pso/snapshotclass.yaml), I get: 
$ k apply -f snapshotclass.yaml
error: unable to recognize "snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"

I have the following snapshot CRDs:
$ k get crds | grep volumesnap
volumesnapshotclasses.snapshot.storage.k8s.io    2020-08-17T21:27:12Z
volumesnapshotcontents.snapshot.storage.k8s.io   2020-08-17T21:27:12Z
volumesnapshots.snapshot.storage.k8s.io          2020-08-17T21:27:12Z

And the snapshot.storage.k8s.io API still looks like it is the alpha. 
$ k api-versions | grep snap
snapshot.storage.k8s.io/v1alpha1

**Comment by Pure-AdamuKaapan** [comment]
@aboje with the new version of k8s and PSO, you'll likely have to remove the old CRDs (`volumesnapshotclasses`, `volumesnapshotcontents`, and `volumesnapshots`) and apply the new ones. You'll also have to install the snapshot controller. Once that's done, the new snapshot class should go in.

The commands to do all of this looks like the following:
```
# Install Beta CRDs
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

# Install Snapshot controller
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-3.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
```

**Comment by aboje** [comment]
Thank you, I agree. Is this also a required addition: 
https://kubernetes-csi.github.io/docs/snapshot-validation-webhook.html

**Comment by aboje** [comment]
Does PSO6 run any checks to see if CRDs, APIs, and other pre-requisites are in place prior to the installation attempt? If not, that would be helpful.

**Comment by Pure-AdamuKaapan** [comment]
I don't believe that's a required addition, no. At the moment we don't have checks in place, but we are working on adding functionality to validate prerequisites and install missing ones.

**Comment by aboje** [comment]
After running those steps, we were able to proceed with the PSO6 final step of applying the snapshotclass.yaml. This was successful. We are now able to create volumesnapshots successfully.
