### ISSUE TITLE
RWX on FlashArray

### ISSUE THREAD

**Issue by aboje** [purestorage/pso-csi#167]
PSO docs indicate that FlashArrays can be used for RWX accessmode on PVCs. Does this require a different storageClass be created? My pvc creation failed with this error:
"failed to provision volume with StorageClass "pure-block": rpc error: code = InvalidArgument desc = mount volume type with block backend and read-write-many access mode is not supported"

PVC:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-rwx
spec:
  storageClassName: pure-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

pure-block StorageClass:
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    csi.storage.k8s.io/fstype: xfs
    meta.helm.sh/release-name: pure-pso
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-15T20:45:35Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: pure-pso
    generator: helm
    kubernetes.io/cluster-service: "true"
    release: pure-pso
  name: pure-block
  resourceVersion: "104787191"
  uid: 0a64621a-0574-4671-a9fc-660273dc0bd9
mountOptions:
- discard
parameters:
  backend: block
  createoptions: -q
  csi.storage.k8s.io/fstype: xfs
provisioner: pure-csi
reclaimPolicy: Delete
volumeBindingMode: Immediate

**Comment by sdodsley** [comment]
See details on how to use FA RWX here: https://github.com/purestorage/pso-csi/blob/master/docs/csi-read-write-many.md

**Comment by aboje** [comment]
Ok, got it. "Specifically, we prohibit mounting a block volume as a filesystem as RWX." 
Thanks for the fast response.
