### ISSUE TITLE
[FB] Storage class to create volumes with hard limits ?

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#171]
I could not find a parameter enabling hard limits on created volumes on flashblade, is it possible ?

**Comment by haibinxie** [comment]
Voice heard, we plan to support it in the next release PSO 6.2 around Aug.

**Comment by dsupure** [comment]
Hi @mscbpi: Sorry the feature cannot make it in the PSO 6.2 release. 
I would suggest you use FA/FB UI to manually enable it.
PSO is going to merge into [portworx](https://portworx.com/). We don't plan to add new features to PSO but we will continue to patch bugs and support customers for any technical issues.

**Comment by pure-jliao** [comment]
will be fixed as enabling hard limit by default in upcoming 6.2.0 GA.
