### ISSUE TITLE
Explanation of DB failover

### ISSUE THREAD

**Issue by jake2184** [purestorage/pso-csi#185]
I'm after a bit of clarity as the resilience/purpose of the cockroach DB volumes in a failover scenario.

I have 2 Pure devices, PureA and PureB, in a k8s cluster. I deploy pso on it, and PureA gets 3 DB volumes and PureB gets 2 DB volumes.

What happens if I loose PureA? Does the database continue to function, or does it require a quorum of the volumes? I'm not clear if they're shards or 5 identical replicas, and if they require quorum or can run independently.

Thanks!

**Comment by pure-jliao** [comment]
if we lose 3 volumes we may hit some issues as it would lose whatever ranges were hosted on those three replicas. the db volumes are 5 replicas. if we have 3 or more replicas we can tolerate full backend failure.
