### ISSUE TITLE
prometheus metrics ?

### ISSUE THREAD

**Issue by menardorama** [purestorage/pso-csi#186]
Does latest version of PSO provide prometheus metrics of pvc usage ?

PSO Explorer don't offer such functionality, pso-analytics was but it's not maintained anymore

Thanks

**Comment by sdodsley** [comment]
The latest version of PSO provides information for `getvolumestats` which can be scraped by the Prometheus Node Exporter.

This [blog post](https://devopscube.com/node-exporter-kubernetes/) has useful information on this.
