### ISSUE TITLE
purestorage pso-db Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by TheBluesTeam** [purestorage/pso-csi#189]
hello i am pure-storage user 

Environment
1. k8s version: v1.20.10
2. node 3ea / master 1ea
3. os version : ubuntu 20.04.3
4. pso version : 6.2.0/6.0.1/6.0.5
5. cni : weave/clium/calico
6. maintenance : vsphere on vm
======================================================
Connect k8s and pure as a test.
but 

**kubectl get pod -n storage**
pso-csi-controller-0                        5/6     Running                        3          2m9s
pso-csi-node-r6frf                          2/3     Running                        3          2m9s
pso-csi-node-sk6qp                       2/3     Running                        3          2m9s
pso-csi-node-vttgc                         2/3     Running                        3          2m9s
pso-db-0-0                                     0/1     Init:CrashLoopBackOff   4          118s
pso-db-1-0                                     0/1     Init:CrashLoopBackOff   4          118s
pso-db-2-0                                     0/1     Init:CrashLoopBackOff   4          118s
pso-db-3-0                                     0/1     Init:CrashLoopBackOff   4          118s
pso-db-4-0                                     0/1     Init:CrashLoopBackOff   4          118s
pso-db-cockroach-operator-65c697676-xlnwr   1/1     Running                 0          2m9s
pso-db-deployer-649bcbf568-dqjbw            1/1     Running                 0          2m9s

**kubectl logs -n storage pso-csi-controller-0 -c pso-csi-container**

time="2021-10-13T08:21:09Z" level=error msg="failed to connect to cockroach" addr="host=pso-db-public.storage port=26257
user=root dbname=pure sslmode=require sslcert=/cockroach/cockroach-certs/client.root.crt sslkey=/cockroach/cockroach-certs/client.root.key sslrootcert=/cockroach/cockroach-certs/ca.crt" 
error="dial tcp: lookup pso-db-public.storage on 10.96.0.10:53: write udp 10.100.31.127:44716->10.96.0.10:53: write: operation not permitted"

time="2021-10-13T08:21:09Z" level=error msg="Failed to instantiate persistent store service in readiness probe, not ready" error="failed to connect to cockroach"

time="2021-10-13T08:21:09Z" level=info msg="Probe indicates plugin is not ready yet, waiting and retrying" error="<nil>" sleep_ms=84235.33392566246 span="{}"

**kubectl logs -n storage pso-csi-node-r6frf** 

time="2021-10-13T08:24:22Z" level=error msg="failed to connect to cockroach" addr="host=pso-db-public.storage port=26257 
user=root dbname=pure sslmode=require sslcert=/cockroach/cockroach-certs/client.root.crt sslkey=/cockroach/cockroach-certs/client.root.key sslrootcert=/cockroach/cockroach-certs/ca.crt" 
error="dial tcp: lookup pso-db-public.storage on 10.96.0.10:53: read udp 10.0.3.241:45466->10.96.0.10:53: i/o timeout"

time="2021-10-13T08:24:22Z" level=error msg="Failed to instantiate persistent store service in readiness probe, not ready" error="failed to connect to cockroach"

time="2021-10-13T08:24:22Z" level=info msg="Probe indicates plugin is not ready yet, waiting and retrying" error="<nil>" sleep_ms=158.62037146736316 span="{}"

**kubectl logs -n storage pso-db-0-0**

Error from server (BadRequest): container "cockroachdb" in pod "pso-db-0-0" is waiting to start: PodInitializing

**Comment by TheBluesTeam** [comment]
ADD LOG 

time="2021-10-14T00:40:50Z" level=error msg="failed to connect to cockroach" addr="host=pso-db-public.pure port=26257 user=root dbname=pure sslmode=require sslcert=/cockroach/cockroach-certs/client.root.crt sslkey=/cockroach/cockroach-certs/client.root.key sslrootcert=/cockroach/cockroach-certs/ca.crt" error="dial tcp 10.98.72.90:26257: connect: connection refused"
time="2021-10-14T00:40:50Z" level=error msg="Failed to instantiate persistent store service in readiness probe, not ready" error="failed to connect to cockroach"
time="2021-10-14T00:40:50Z" level=info msg="Probe indicates plugin is not ready yet, waiting and retrying" error="<nil>" sleep_ms=141367.61576874158 span="{}"

**Comment by TheBluesTeam** [comment]
[pso-logs-2021.10.14-11.19.31.zip](https://github.com/purestorage/pso-csi/files/7343096/pso-logs-2021.10.14-11.19.31.zip)

**Comment by L4rS6** [comment]
I run into the same issue with the following cluster:

- k8s Version: 1.21.5
- OS: Ubuntu 20.04.3 LTS
- pure/pure-pso Version : 6.2.0
- CNI : Calico

Let me know if I can provide any further information.

**Comment by L4rS6** [comment]
> @L4rS6 there's a known one caused by readiness probe failure threshold starting k8s 1.21, could you try to add this fix to your cluster and see? #188

@pure-jliao I just tried that fix, but the problem remains the same. Do you need further information?
