### ISSUE TITLE
PSO v6.2.1 Release

### ISSUE THREAD

**Issue by dsupure** [purestorage/pso-csi#197]
**PSO v6.2.1 Release**

Fixes and improvements: 
* Fix KB unit issue for NodeGetVolumeStats CSI call
* Support FlashBlade Safe Mode.
* Upgrade apiextensions.k8s.io API version from v1beta1 to v1.
* #196
* Upgrade CSIDriver apiVersion from v1beta1 to v1
* FibreChannel + NVME bug fixes.
* Fix volume resize failures

**Comment by aboje** [comment]
Is this release k8s 1.22 compatible?

**Comment by dsupure** [comment]
@aboje : No, we found an issue during the k8s 1.22 test. We decide to ship the 6.2.1 patches first.
K8s 1.22 support will be in 6.2.2 shortly.

**Comment by fersan1985** [comment]
I have this version running on my K8s v1.22.1 (Rocky Linux + multipath workaround + flannel issues + 2 days of troubleshooting with tears and blood)

![Screen Shot 2021-11-18 at 00 43 25](https://user-images.githubusercontent.com/72047538/142347817-c82b6404-5a37-4ba9-9bd8-4f24dd6b2e89.png)
.)
