### ISSUE TITLE
Vulnerabilities detected in livenessprobe default image

### ISSUE THREAD

**Issue by djonnalaf5** [purestorage/pso-csi#207]
Hello, 

We are using the default/recommended version for the livenessprobe image at https://github.com/purestorage/pso-csi/blob/d6da3f5c348644a73fbff24ad0e2c41ef8a17438/pure-pso/templates/plugin/node-server.yaml#L180
and there are multiple vulnerabilities detected in that image.  This image needs to be updated and please suggest the default image. 

Image: quay.io/k8scsi/livenessprobe:v2.0.0

Found vulnerabilities 

![image](https://user-images.githubusercontent.com/100810989/156469174-c58798df-84b3-409c-b8e5-956dd0542fa0.png)

**Comment by dsupure** [comment]
Hi @djonnalaf5 : Yes, we plan to do a patch release to fix the vulnerability issues. It should be around late May or early June.
