### ISSUE TITLE
Kubernetes 1.22 fails, because still using v1beta1 API?

### ISSUE THREAD

**Issue by rickerc** [purestorage/pso-csi#208]
In the changelog for 6.2.1 I see:

* Upgrade CSIDriver apiVersion from v1beta1 to v1

However, when I deploy 6.2.2 on a k8s 1.22 cluster, I see this warning during install:

W0331 17:24:55.378092  136256 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
W0331 17:24:55.482359  136256 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver

And then volume creation fails, and from the logs appears to be failing because it can't hand off to CSI.... (and I still see beta1 annotations on PVCs etc)

Should 6.2.2 work with k8s 1.22? And should I be getting that warning still about v1beta1 with 6.2.2?

**Comment by gaima8** [comment]
Not sure if I'm suffering from the same problem as you @rickerc but I'm unable to get PVCs in a brand new k8s 1.22 cluster.

A volume is provisioned (in the flasharray) and bound to a pod (in k8s). But the volume (flasharray) doesn't get connected to a host (iSCSI), so no block device is seen by the k8s node.
The pod logs are... interesting? I guess. The pso-db thing is running with flasharray volumes created and attached to the pods.

- pso-csi-container
```
time="2022-04-19T18:07:11Z" level=error msg="waiters found" bucket= req="(*csi.ProbeRequest) " span="{}" waiters=1
time="2022-04-19T18:07:11Z" level=error msg="failed to queue request" error="rpc error: code = Aborted desc = requests pending" req="(*csi.ProbeRequest) " span="{}"
time="2022-04-19T18:07:11Z" level=error msg="GRPC handler error" error="rpc error: code = Aborted desc = requests pending" method=/csi.v1.Identity/Probe request= span="{}"
```
- csi-provisioner
```
... Successfully provisioned volume ...
```
- csi-snapshotter
```
E0419 18:08:26.484128       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```
- csi-attacher
```
E0419 18:09:11.610051       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0419 18:09:11.610094       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
```
- liveness-probe
```
E0419 18:09:29.007023       1 main.go:55] health check failed: rpc error: code = Aborted desc = requests pending
```

I'd give Portworx a go but that doesn't support providing a CSI yet.

**Comment by rickerc** [comment]
That looks like the same failure I was seeing. 

FWIW, Portworx does have a CSI variant now -- https://central.portworx.com/specGen/wizard and select the "Portworx CSI for FlashArray and FlashBlade" to try it. It's not 1:1 feature parity with PSO CSI, though, so may or may not be a suitable alternative for you....

**Comment by dsupure** [comment]
@rickerc, @gaima8 : 
PSO doesn't support 1.22 yet. It's not because of the v1beta1, the issue is due to csi.ProbeRequest. 

PSO is integrating into Portworx. We don't have plan to support higher k8s versions unless there are major vulnerability concerns of current k8s versions.  Please contact Pure/Portworx support to explore Portworx options.

I'll close the issue in the next few days if you don't have any further questions
