### ISSUE TITLE
Question: Import pv/pvc created with 5.x

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#87]
When installing PSO 6.x, shall we recreate every volume ?

Also: 
despite what the doc says [here](https://github.com/purestorage/pso-csi/blob/master/docs/custom-storageclasses.md#provided-storage-classes) `pure` storage class is not created by default anymore. Nor is `storageClass:` available in `values.yaml` (documented [here](https://github.com/purestorage/pso-csi/blob/master/docs/custom-storageclasses.md#default-storageclass) but not [there](https://github.com/purestorage/pso-csi/tree/master/pure-pso))

I have recreated the storage class manually.

I have a bunch of errors but for some reasons volume is actually attached and pod is working:

`AttachVolume.Attach failed for volume "pvc-b74531d6-2b86-4a4c-9bce-8c4ad1f79cf3" : rpc error: code = NotFound desc = Failed to import backend volume pure-csi/pvc-b74531d6-2b86-4a4c-9bce-8c4ad1f79cf3, not found`

**Comment by sdodsley** [comment]
The `pure1 storageClass was deprecated so considerable time ago and finally removed in PSO 6. These documentation glitches have slipped through and will be resolved. Thank you for pointing them out.
There is no official upgrade path from PSO 5.x to 6.0.x at this time. We are working on a solution, but in the interim it should be possible to use a similar process to the one described for the Flex to PSO upgrade: https://blog.2vcps.io/2020/06/10/flex-is-dead-long-live-csi/.
For your errors we would need to know much more detail on the steps you took and obtain full logs from the node and controller pods to diagnose.

**Comment by mscbpi** [comment]
In fact my pod were running with attached volumes until they have to restart, then CSI won't find existing volumes.

It was unclear whether the upgrade was not supported in terms of helm chart / CSI plugin upgrade or PV/PVC management migration and existing data. So I consider old PV/PVC have to be migrated manually by deleting them (with retain policy) and re-importing them (as per your doc and below).

- I had not set `clusterID` so my volumes where prefixed with pure-csi (pure-csi-pvc-xxx) and now it is myprefix-pvc-xxx.
- Interesting enough, I could not set "pure-csi" as clusterID as it refuses "-" char
- I don't know if this is the cause or, as you mention, the previous volumes are just unknown to the new operator (not imported in the DB) and won't be usable until reimport.

>Scale down your applications so that no pods are using the FlexDriver managed PVCs and PVs.
Uninstall your FlexDriver – don’t worry all your PVs and PVCs will remain and the applications using them won’t notice.
Install the CSI based driver – now all new PVs will be managed by this new driver.
Identify your PVs that were created by the FlexDriver.
Patch the PV definition to ensure it doesn’t get automatically deleted by Kubernetes.
Delete the PVC and then the PV – sounds scary, but the previous patch command means that underlying volume on the backend storage is retained
Import the storage volume back into Kubernetes and under the CSI drivers control – this is where you need PSO v5.2.0 or higher…
Scale back up your applications.

**Comment by mscbpi** [comment]
Before closing this issue just to be clear:

- PV/PVC created with 5.x should be deleted and imported manually whatever happens ?
- Or did I meet this situation because clusterID (then prefix) changed ?

I happen to have recreated volumes and migrated data when needed, when possible, for most of them (quicker than PV import).

**Comment by mscbpi** [comment]
@sdodsley I closed by mistake, also answer edited. Thanks for your support.

**Comment by sdodsley** [comment]
All references to the `pure` storage class have now been removed from the repo by #88 . Thanks for pointing this oversight to us.

We are still working on an official upgrade path from 5 to 6 and will keep you informed.

**Comment by mscbpi** [comment]
We've upgraded to 6.x a while ago with  manual imports of existing pvc we wanted to keep. 

It seems 6.1 has an upgrade path from 5.x

So this issue can be closed
