### ISSUE TITLE
Question: pso reinstallation

### ISSUE THREAD

**Issue by mscbpi** [purestorage/pso-csi#92]
Question:

What happens if we delete completely the `pso` helm charts and leave existing volumes, and then reinstall the helm chart (same version), do we recover our setup ?

**Comment by Pure-AdamuKaapan** [comment]
You will indeed recover your setup, assuming you leave the volumes and cluster ID with the same name. PSO on startup will scan for all volumes that match the same cluster ID and use them to start up, then will do any required scaling after a successful startup.

**Comment by mscbpi** [comment]
Ok ! This leads me to the following question: if by any chance my  pso-5.x-created-volumes would have the correct prefix/clusterID, would they be imported automatically ?

**Comment by Pure-AdamuKaapan** [comment]
Unfortunately not yet. However, we are working on a more streamlined migration path from PSO 5.x to 6.x. That being said, if you have an urgent need to migrate, you can follow the instructions at https://github.com/purestorage/pso-csi/blob/master/docs/csi-volume-import.md. Just note that it will be a disruptive migration, as workloads will have to be re-mounted.

**Comment by mscbpi** [comment]
Yes I had done that just wondering if I could have avoided it. thanks !
