### ISSUE TITLE
Release v6.0.3

### ISSUE THREAD

**Issue by DIMPLY** [purestorage/pso-csi#95]
#### Enhancements:

* Enabled support to import snapshots from Pure Flash Array(FA). This applies to snapshots that were created directly on the Flash Array outside of K8S
* Added support for Platform9.
* Improved handling of NFS versions and support for mounting volumes that were provisioned prioir to NFS v4.1 upgrade
* Fixed race condition issue in cockrachdb operator that created more pods than needed
* Fixed the bug: log level in values.yaml not honored
* Support for REST API v2.0

**Comment by sdodsley** [comment]
Are we going to include the cockroach resource limits exposure as discussed??

**Comment by DIMPLY** [comment]
@sdodsley Are you talking about the memory leak issue? I remember a fix was reversed, so I didn't included. Is there a new fix included in the code? (I remember David wanted to modify something in values.yaml to set a limit for this.)

**Comment by sdodsley** [comment]
It's not a leak, but a bad implementation that needs fixing. As it's relatively simple we should wait and include in this release

**Comment by dsupure** [comment]
As I mentioned in the team channel. Users today can rein them memory using `database.resources.memory.limits` in `values.yaml`. We can do another enhancement to expose the default values (`--cache .25 --max-sql-memory .25`), which is hard-coded in the cockroach-operator today, but I don't think it urgent to do so. We can do in the next release. IMHO, the release is good to go, we just need to have a full/successful CI test.

**Comment by dsupure** [comment]
Aslo, what is this one, @DIMPLY ?
* Optimization by reducing the number of RESTful API calls

**Comment by sdodsley** [comment]
These database resource limits need to be documented then.

**Comment by DIMPLY** [comment]
@dsupure I originally put it as "En’s fix for the TestAttachAndDetachStorm" according to our Slack discussion, but it's actually reducing all rest api calls, not only for TestAttachAndDetachStorm. TestAttachAndDetachStorm just happens to put more loads on the REST server.
